### ISSUE TITLE
Add CLI option to build multiple executables

### ISSUE THREAD

**Issue by jmarsh24** [nalgeon/sqlpkg-cli#16] opened 2024-01-19 15:35 UTC
I'm using a gem https://github.com/fractaledmind/sqlpkg-ruby to install SQLite extensions. Locally everything works but in CI where I'm running an Ubuntu image it requires files that Mac OS doesn't generate. 

I have highlighted the error below.  I have a `.dylib` but as you can see, there is no `dylib.so` file because it was built on mac.
It would be great to pass an option so that I can build for all multiple platforms.

```
bin/rails db:setup && bin/rspec --format documentation
  bin/rails db:setup && bin/rspec --format documentation
  shell: /usr/bin/bash -e {0}
  env:
    RAILS_ENV: test
.sqlpkg/asg017/ulid/ulid0.dylib.so: cannot open shared object file: No such file or directory
Couldn't create './db/test/data.sqlite3' database. Please check your configuration.
bin/rails aborted!
.sqlpkg/asg017/ulid/ulid0.dylib.so: cannot open shared object file: No such file or directory
```

**Comment by fractaledmind** [comment] 2024-01-19 15:37
Yeah, this will be a common pain point for people that want to use `sqlpkg` _within_ a project (and not globally). Since the `.json` manifest file you have in the registry already has all of information for each file needed on each platform, it shouldn't be too difficult to simply download all of them if a certain flag is passed on `install`. WDYT?

**Comment by nalgeon** [comment] 2024-01-19 16:34
Not sure I understand the root cause here. `sqlpkg install` downloads the binaries for the host OS, so it works on both macOS and Ubuntu. Where does this `.sqlpkg/asg017/ulid/ulid0.dylib.so` come from on Ubuntu, is it something `sqlpkg-ruby` does?

**Comment by fractaledmind** [comment] 2024-01-22 23:06
@nalgeon Let me try to explain: 

Many web application developers want to "vendor" external dependencies in their source repository, such that the dependency can be integrated into their application and run in their local development environment, the CI environment, and their production environment. Often, those 3 environments are running on at least 2 different host operating systems (MacOS and some distro of Linux, let's say). 

When running `sqlpkg install {some-extension}` in local development environment, `sqlpkg` will install only the binaries needed for that operating system. When you then have your repository checked out and run in CI, if CI is running on a different operating system, it will not have the binaries needed for the extension and your app will fail to boot.

The report is saying that CI is failing because `.sqlpkg/asg017/ulid/ulid0.dylib.so` is **not** present in the `.sqlpkg` directory in the CI environment, because it isn't. The ULID extension was installed on MacOS, and so only a `.dylib` binary was downloaded. 

The ask is to provide an option to pass to `sqlpkg install` to force _all_ binaries to be downloaded so that the vendor extension can be loaded and run in all host operating systems that the repository may be deployed to.

**Comment by nalgeon** [comment] 2024-01-23 04:13
The way I see it, the job of the package manager is to install binaries for the specific OS it runs on. That's how all package managers work, as far as I know.

It should not be a problem when working on multiple OSs, because all you have to do is run "install" on your OS before using the package.

Now the thing I do not understand is where the `.sqlpkg/asg017/ulid/ulid0.dylib.so` comes from. It's not a valid extension path.

How can I reproduce the described problem?

**Comment by fractaledmind** [comment] 2024-01-23 09:54
Yes, sorry for the confusion. Let me explain. As you might recall, I have a Ruby gem the provides `sqlpkg` to Ruby projects (https://github.com/fractaledmind/sqlpkg-ruby). When you install the gem, it does three things:

1. creates an empty `.sqlpkg/` directory, which ensures that `sqlpkg` will run in "project scope" and not "global scope" (see [the sqlpkg-cli README](https://github.com/nalgeon/sqlpkg-cli#project-vs-global-scope) for more information)
2. creates an empty `sqlpkg.lock` file, which `sqlpkg` will use to store information about the installed packages (see [the sqlpkg-cli README](https://github.com/nalgeon/sqlpkg-cli#lockfile) for more information)
3. creates an initializer file at `config/initializers/sqlpkg.rb` which will patch the `SQLite3Adapter` to automatically load the extensions installed in the `.sqlpkg/` directory whenever the database is opened

It is point three that is most relevant here. Here is the relevant code executed there:
```ruby
@raw_connection.enable_load_extension(true)
Dir.glob(".sqlpkg/**/*.{dll,so,dylib}") do |extension_path|
  @raw_connection.load_extension(extension_path)
end
@raw_connection.enable_load_extension(false)
```

You will see that we are simply "glob-grabbing" the binaries in the project-scope `.sqlpkg` directory. We then try to load those extension binaries. When you install an extension on MacOS (like `asg017/ulid`), you get the binary executable installed at `.sqlpkg/asg017/ulid/ulid0.dylib`. In GitHub Actions, the glob grabs that file path and passes it to `load_extension`, but when SQLite tries to load the extension it automatically presumes that this extension binary is for Linux/Ubuntu. I don't know where, in SQLite or in the sqlite3-ruby gem, but one of those layers assumes that this is a filename missing the extension needed (`.so`) and tries to find the expected file by taking the file name and adding the extension. Thus, it tries to load `.sqlpkg/asg017/ulid/ulid0.dylib.so`, which naturally is a file that doesn't exist.

**Comment by nalgeon** [comment] 2024-01-23 10:09
Sorry, I'm still confused.

> When you install an extension on MacOS (like asg017/ulid), you get the binary executable installed at .sqlpkg/asg017/ulid/ulid0.dylib. In GitHub Actions, the glob grabs that file path and passes it to load_extension

I understand the macOS part. However, why does the GitHub Actions (running on Ubuntu) grab the `.dylib` file, where does it come from? There should be no `.dylib` files on the Ubuntu machine, so the question is how do they get there?

**Comment by fractaledmind** [comment] 2024-01-23 10:29
They are committed to the repository. The `.sqlpkg` directory is a part of the repository and committed. The idea is to "vendor" these extensions and make the application repository portable.

**Comment by nalgeon** [comment] 2024-01-23 10:42
Okay, I understand now, thank you.

I'm not sure if committing platform-specific binaries is a good idea. Would you also commit platform-specific Ruby packages from third parties too? How would you make `gem install` to download binaries for both macOS and Ubuntu?

**Comment by nalgeon** [comment] 2024-01-23 12:46
Thank you! I'm going to close this issue, since downloading a single platform-specific binary (and not all available binaries) is how all package managers work, as far as I know. `sqlpkg` is no different.

**Closed by nalgeon** 2024-01-23 12:46 UTC
